# Periodically Update Predictions
name: updatepredictions
on:
  push:
    branches: main
  #schedule:
    #- cron: '0 22 * * *'
  #workflow_dispatch:
jobs:
  build:
    runs-on: macos-latest
    env:
      TWITTER_CONSUMER_API_KEY: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
      TWITTER_CONSUMER_API_SECRET: ${{ secrets.TWITTER_CONSUMER_API_SECRET }}
      TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
      TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}    
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master
      - name: install packages
        run: |
          R -e 'install.packages("tidyverse")'
          R -e 'install.packages("zoo")'
          R -e 'install.packages("lubridate")'
          R -e 'install.packages("forecast")'
          R -e 'install.packages("xts")'
          R -e 'install.packages("ggthemes")'
          R -e 'install.packages("rtweet")'
          R -e 'install.packages("Metrics")'
      - name: Run R script
        run: Rscript covidpredictions_auto.R
      - name: Commit results
        run: |
          git config --global user.email "jusmith@wlu.ca"
          git config --global user.name "Justin Smith"
          git add 'data/*.png'
          git commit -m "Update All Plots" || echo "No changes to commit"
          git push origin || echo "No changes to commit"
